name: Continuous build - conda

on:
  schedule:
    - cron: "1 1 1 */1 *"
  push:
    branches: [ main, dev, pg* ]
  pull_request:
    branches: [ main, dev, pg* ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.9"]
#    installing nwbe
    steps:
    - uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: conda-forge
    - uses: actions/checkout@v3

    # required because the version of git-annex in Ubuntu is too old.
    - name: Install datalad
      run: conda install -c conda-forge datalad

    - name: Install additional Python dependencies
      run: |
        pip install wheel
        pip install --requirement requirements.txt --quiet
        pip list

    - name: Install h5py with ROS3 driver
      run: |
        pip uninstall -y h5py
        conda install -c conda-forge h5py

    - name: Configure Git
      run: |
        git config --global user.email "github_ci@test.test"
        git config --global user.name "github ci"
#   cloning nwbe here
    - name: Tests
      run: |
        echo Testing scripts...
        python nwb_table_readme.py --dandiset_limit
        python nwb_table_readme.py --update_readme_only 
#        python validate_and_test_nwb.py --test --succint

    - name: Final file info
      run: |
        ls -alt
        ls -alt validation_folder
        df -h
        du -h

    - name: Final version info
      run: |
        pip list
