name: Build Docker

on:
  schedule:
    - cron: "1 1 1 */1 *"
  push:
    branches: [ main, dev, fix* ]
  pull_request:
    branches: [ main, dev, fix* ]

jobs:
  build:

    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Build Docker image
      run: |
        ./generateDocker.sh
        docker exec -it da /bin/sh -c 'python -V'
    - name: Test just generate readme
      run: |
      
        echo Testing generation of readme...
        docker exec -it da /bin/sh -c 'python testing/nwb_table_readme.py --update_readme_only'
        ls -alt validation_folder
      
    - name: Final version info
      run: |
        docker images
        docker system df 
