name: Build Docker

on:
  schedule:
    - cron: "1 1 1 */1 *"
  push:
    branches: [ main, dev, fix* ]
  pull_request:
    branches: [ main, dev, fix* ]

jobs:
  build:

    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Build Docker image
      run: |
        ./generateDocker.sh
        docker exec -i da /bin/sh -c 'python -V'
        
    - name: Test just generate readme
      run: |
      
        echo Testing generation of readme...
        docker exec -i da /bin/sh -c 'python testing/nwb_table_readme.py --update_readme_only'
        docker exec -i da /bin/sh -c 'ls -alt testing/validation_folder'
        
    - name: Test running the nwbe docker inside
      run: |
      
        echo Testing running nwbe container
        docker exec -di da /bin/sh -c 'docker run -i --name=nwbe -v "$(pwd)"testing:/home/jovyan/nwb-explorer/testing -v /tmp:/home/jovyan/nwb-explorer/tmp nwbe'

    - name: Testing on limited number of dandisets
      run: |
      
        docker exec -i da /bin/sh -c 'python testing/nwb_table_readme.py --dandiset_limit'
        docker exec -i da /bin/sh -c 'ls -alt testing'
        
        
    - name: Testing on limited number of dandisets with Docker
      run: |
      
        echo Testing running nwbe container
        docker exec -i da /bin/sh -c 'python testing/nwb_table_readme.py --dandiset_limit --docker_test'
        docker exec -i da /bin/sh -c 'ls -alt testing'
      
    - name: Final version info
      run: |
        docker images
        docker system df 
